/* Public method content from the existing site; illustrative light relationships. */
(()=>{'use strict';
const {raw,links}=window.OSL_METHOD,section=document.querySelector('.fabric'),layer=document.querySelector('.woven-nodes'),svg=document.querySelector('.woven-network svg'),method=document.querySelector('#woven-method'),detail=method.querySelector('.woven-detail'),directory=method.querySelector('.method-directory>div'),directoryLabel=method.querySelector('.directory-label');
// A hub-and-field constellation: Human Judgment sits beneath the central suspension point,
// while tools spread irregularly across both textile spans instead of forming a diagonal chain.
const positions=[[.42,.23],[.50,.36],[.30,.26],[.16,.23],[.24,.34],[.38,.42],[.55,.58],[.66,.34],[.72,.48],[.82,.33],[.88,.52],[.46,.52],[.62,.68],[.78,.66],[.32,.46],[.85,.24],[.20,.42],[.56,.20],[.93,.42],[.69,.76],[.86,.72]];
const lightDepth=[.68,.82,.58,.72,.64,.76,.88,.62,.84,.66,.78,.61,.83,.69,.73,.57,.65,.80,.60,.75,.67];
let route=[],tracePaths=[],traceTime=0,traceLast=0,traceRunning=false;
let selected=null,hover=null,filter='all',frame=0,visible=true,width=0,height=0,mobile=false;
const nodes=raw.map((r,i)=>({id:i,name:r[0],territory:r[1],type:r[2],description:r[3],uv:positions[i],experimental:[18,19,20].includes(i),dormant:[15,16].includes(i)}));
const edges=links.filter(([a,b])=>a<nodes.length&&b<nodes.length).map(([a,b])=>{const p=document.createElementNS('http://www.w3.org/2000/svg','path');svg.firstElementChild.append(p);return{a,b,path:p}});
const neighbors=i=>edges.filter(e=>e.a===i||e.b===i).map(e=>e.a===i?e.b:e.a);

// Short editorial routes show a clear operating model, not a literal execution log.
const routes=[[0,17,1,11,12],[0,17,1,11,12],[0,2,17],[0,3,17],[0,4,17],[0,5,17],[0,6,17],[0,7,17],[0,8,17,12],[0,9,17],[0,10,17],[0,17,1,11,12],[0,17,1,11,12],[0,17,1,11,12,13],[0,14,17],[15],[16],[0,17],[0,18,17],[0,19,17],[0,20,17]];
const ns='http://www.w3.org/2000/svg',traceLayer=document.createElementNS(ns,'g');traceLayer.classList.add('tool-traces');svg.append(traceLayer);
const traceHead=document.createElementNS(ns,'circle');traceHead.setAttribute('r','3.5');traceHead.classList.add('tool-trace-head');svg.append(traceHead);traceHead.style.display='none';
const routeCaption=document.createElement('p');routeCaption.className='method-route';routeCaption.textContent='CORE PATH · Plan → Decide → Make → Publish';detail.append(routeCaption);
function startTrace(i){route=routes[i];traceTime=0;traceLast=0;traceRunning=true;traceLayer.replaceChildren();tracePaths=route.slice(1).map(()=>{const p=document.createElementNS(ns,'path');p.setAttribute('pathLength','1');traceLayer.append(p);return p});
routeCaption.textContent=nodes[i].dormant?'Explored, then set aside — not part of the deployed system.':i===8?'PATH · Plan in ChatGPT → Call Higgsfield through the connector → Review with Human Judgment → Publish':i===0?'CORE PATH · Plan in ChatGPT → Apply Human Judgment → Build → Preserve → Publish':'PATH · ChatGPT sets direction → '+nodes[i].name+' is called → Human Judgment decides what moves forward';
svg.dataset.traceSelection=String(i);drawTrace(performance.now());}
function drawTrace(now){const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
if(traceRunning){const dt=traceLast?Math.min((now-traceLast)/1000,.05):0;traceLast=now;if(section.dataset.motion!=='paused')traceTime+=dt;if(reduced)traceTime=route.length;}
const duration=.72,progress=traceTime/duration;svg.dataset.traceProgress=String(progress);
const current=route[Math.min(Math.floor(progress),route.length-1)];
for(const n of nodes){n.button.classList.toggle('trace-current',n.id===current&&route.length>0);n.button.classList.toggle('trace-visited',route.includes(n.id)&&route.indexOf(n.id)<=progress);}
traceHead.style.display='none';
tracePaths.forEach((p,k)=>{const a=nodes[route[k]].xy,b=nodes[route[k+1]].xy;if(!a||!b)return;const bend=Math.min(24,Math.abs(a.x-b.x)*.1);p.setAttribute('d',`M${a.x},${a.y} Q${(a.x+b.x)/2},${(a.y+b.y)/2+bend} ${b.x},${b.y}`);const u=Math.max(0,Math.min(1,progress-k));p.style.strokeDashoffset=String(1-u);p.style.opacity=u>0?'1':'0';
if(u>0&&u<1){const pos=p.getPointAtLength(p.getTotalLength()*u);traceHead.setAttribute('cx',pos.x);traceHead.setAttribute('cy',pos.y);traceHead.style.display='';}});
if(progress>=Math.max(1,route.length-1)){traceRunning=false;svg.dataset.traceState='complete'}else svg.dataset.traceState='playing';}

const coreIds=[0,17,1,11,12];
function matches(n){if(filter!=='all')return n.territory===filter||[0,17].includes(n.id);if(selected!==null)return n.id===selected||neighbors(selected).includes(n.id)||route.includes(n.id);return coreIds.includes(n.id)}
function role(n){return n.dormant?'Tested → moved on':n.experimental?'Supporting experiment':n.type}
function show(i,scroll=false){selected=i;detail.classList.remove('is-overview');detail.querySelector('.method-status').hidden=false;detail.querySelector('h3').hidden=false;const n=nodes[i],discipline=n.id===17?'Human Judgment':n.territory[0]+n.territory.slice(1).toLowerCase();detail.querySelector('.method-status').textContent='System / '+discipline;detail.querySelector('h3').textContent=n.name;detail.querySelector('.method-description').textContent=n.description;const connections=method.querySelector('.method-connections');connections.replaceChildren();
for(const id of neighbors(i)){const b=document.createElement('button');b.type='button';b.textContent=nodes[id].name+' ↗';b.setAttribute('aria-label','Explore connected entry: '+nodes[id].name);b.addEventListener('click',()=>show(id));connections.append(b)}
method.querySelector('.method-clear').hidden=false;startTrace(i);refresh();if(scroll){method.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'end'});detail.querySelector('h3').tabIndex=-1;detail.querySelector('h3').focus({preventScroll:true})}}
function refresh(){directoryLabel.textContent=selected!==null&&filter==='all'?'Connected path':filter==='all'?'Core path · 5 parts':filter[0]+filter.slice(1).toLowerCase()+' · selected sources';for(const n of nodes){n.button.setAttribute('aria-pressed',String(n.id===selected));n.entry.setAttribute('aria-pressed',String(n.id===selected));n.entry.hidden=!matches(n)&&n.id!==selected;n.button.hidden=(!matches(n)||n.dormant||n.experimental||(mobile&&![0,1,2,6,8,11,12,17].includes(n.id)))&&n.id!==selected&&!route.includes(n.id);}wake()}
for(const n of nodes){const b=document.createElement('button');b.type='button';b.className='woven-node';b.dataset.type=n.type;b.dataset.node=String(n.id);b.style.setProperty('--light-alpha',String(lightDepth[n.id]));b.style.setProperty('--thread-alpha',String(.5-lightDepth[n.id]*.28));b.setAttribute('aria-label',n.name+' — '+role(n));const label=document.createElement('span');label.textContent=n.name;b.append(label);b.addEventListener('click',()=>show(n.id,true));b.addEventListener('pointerenter',()=>{hover=n.id;wake()});b.addEventListener('pointerleave',()=>{hover=null;wake()});b.addEventListener('focus',()=>{hover=n.id;wake()});b.addEventListener('blur',()=>{hover=null;wake()});layer.append(b);n.button=b;
const entry=document.createElement('button');entry.type='button';entry.className='method-entry';entry.textContent=n.name;entry.setAttribute('aria-label',n.name+' — '+role(n)+' — '+n.territory.toLowerCase());entry.addEventListener('click',()=>show(n.id));directory.append(entry);n.entry=entry;}
const categoryCopy={all:['System / Full system','Full system','ChatGPT holds the plan and coordinates models, APIs, and connections; human judgment guides what moves forward.','CORE PATH · Plan → Decide → Make → Publish'],THINK:['System / Think','Think','ChatGPT frames the problem; selected sources broaden the view; human judgment sets direction.','FOUNDATION · A clear brief makes every later tool more useful.'],DESIGN:['System / Design','Design','ChatGPT carries the brief into selected design capabilities; human judgment protects coherence and taste.','CONNECTION · Specialist capabilities enter only when the plan calls for them.'],BUILD:['System / Build','Build','ChatGPT carries approved decisions into implementation; human judgment validates; GitHub preserves the work.','FOUNDATION · Direction becomes a durable working system.'],CREATE:['System / Create','Create','ChatGPT calls selected media capabilities; human judgment chooses what advances.','CONNECTION · Higgsfield and other media capabilities extend the plan, not replace it.'],PUBLISH:['System / Publish','Publish','ChatGPT coordinates release tasks; human judgment approves; GitHub, Netlify, and Cloudflare deliver.','OUTCOME · One approved system moves into the world.']};
function showCategory(key){selected=hover=null;route=[];traceRunning=false;tracePaths=[];traceLayer.replaceChildren();traceHead.style.display='none';const copy=categoryCopy[key];routeCaption.textContent=copy[3];detail.classList.remove('is-overview');detail.querySelector('.method-status').hidden=false;detail.querySelector('h3').hidden=false;detail.querySelector('.method-status').textContent=copy[0];detail.querySelector('h3').textContent=copy[1];detail.querySelector('.method-description').textContent=copy[2];method.querySelector('.method-connections').replaceChildren();method.querySelector('.method-clear').hidden=true;method.querySelector('.method-expanded').scrollTop=0;}
for(const [key,label] of [['all','Full system'],['THINK','Think'],['DESIGN','Design'],['BUILD','Build'],['CREATE','Create'],['PUBLISH','Publish']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.filter=key;b.setAttribute('aria-pressed',String(key==='all'));b.addEventListener('click',()=>{filter=key;showCategory(key);method.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));method.querySelector('.method-directory').open=true;refresh()});method.querySelector('.method-filters').append(b)}
method.querySelector('.method-clear').addEventListener('click',()=>{filter='all';showCategory('all');method.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.filter==='all')));refresh()});
// Invert the same bounded textile displacement used by fabric-breath.js, so
// lights stay embedded in the moving plate instead of drifting over it.
function displacement(p,t,drop){const pocket=(cx,cy,sx,sy)=>Math.exp(-1.7*(((p[0]-cx)/sx)**2+((p[1]-cy)/sy)**2));const a=pocket(.45,.28,.22,.28),b=pocket(.68,.49,.23,.32),c=pocket(.85,.64,.22,.32);const smooth=(lo,hi,v)=>{const x=Math.max(0,Math.min(1,(v-lo)/(hi-lo)));return x*x*(3-2*x)};const edge=smooth(0,.1,p[0])*(1-smooth(.9,1,p[0]))*smooth(0,.1,p[1]);const leftSpan=1-smooth(.08,.63,p[0]),hanging=smooth(.01,.72,p[1]),settledWave=.012*Math.sin(t*.29+p[0]*3.1+1.2)*leftSpan*drop;return[((.006*a*Math.cos(t*.37)+.008*b*Math.sin(t*.32+1)-.007*c*Math.cos(t*.35+2))*edge)+.012*leftSpan*(p[1]-.18)*drop,((.021*a*Math.sin(t*.46+.3)+.029*b*Math.sin(t*.39+2)+.024*c*Math.sin(t*.43+4)+.0024*Math.sin(p[0]*18-t*.66)*Math.sin(p[1]*9+t*.23)*(a+b+c))*edge)-.145*leftSpan*(.34+.66*hanging)*drop+settledWave]}
function point(uv,t,drop){let p=[...uv];for(let k=0;k<4;k++){const d=displacement(p,t,drop);p=[uv[0]-d[0],uv[1]-d[1]]}const image=section.querySelector('img.art');const iw=image.naturalWidth||1672,ih=image.naturalHeight||941,s=Math.max(width/iw,height/ih),ox=(width-iw*s)*(mobile?.72:.5),oy=document.body.classList.contains('exploring-system')?0:(height-ih*s)*.5;return{x:p[0]*iw*s+ox,y:p[1]*ih*s+oy}}
function embedLights(){const image=section.querySelector('img.art');if(!image.naturalWidth)return;const sample=document.createElement('canvas'),sw=320,sh=Math.round(sw*image.naturalHeight/image.naturalWidth);sample.width=sw;sample.height=sh;const ctx=sample.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,sw,sh);const pixels=ctx.getImageData(0,0,sw,sh).data;const onFabric=(x,y)=>{const px=Math.max(0,Math.min(sw-1,Math.round(x*(sw-1)))),py=Math.max(0,Math.min(sh-1,Math.round(y*(sh-1)))),k=(py*sw+px)*4;return pixels[k]*.2126+pixels[k+1]*.7152+pixels[k+2]*.0722>72};for(const n of nodes){let [x,y]=n.uv,steps=0,found=onFabric(x,y);while(!found&&steps++<18){y+=.006;found=onFabric(x,y)}n.uv=[x,found?Math.min(.9,y+(steps?0.014:0)):n.uv[1]]}wake()}
function draw(){frame=0;if(!visible||document.hidden)return;const breath=document.querySelector('#fabric-breath'),t=Number(breath.dataset.time)||0,drop=Number(breath.dataset.drop)||0,f=hover??selected;for(const n of nodes){n.xy=point(n.uv,t,drop);n.button.style.left=n.xy.x+'px';n.button.style.top=n.xy.y+'px';n.button.dataset.labelLeft=String(n.xy.x>width*.75);n.button.classList.toggle('is-muted',f!==null&&f!==n.id&&!neighbors(f).includes(n.id)&&!route.includes(n.id));}
for(const e of edges){const a=nodes[e.a],b=nodes[e.b];e.path.style.display=a.button.hidden||b.button.hidden?'none':'';const bend=(e.b%2?1:-1)*Math.min(28,Math.abs(a.xy.x-b.xy.x)*.12);e.path.setAttribute('d',`M${a.xy.x},${a.xy.y} Q${(a.xy.x+b.xy.x)/2},${(a.xy.y+b.xy.y)/2+bend} ${b.xy.x},${b.xy.y}`);e.path.classList.toggle('connected',f!==null&&(e.a===f||e.b===f))}
drawTrace(performance.now());if(section.dataset.motion==='playing'||(traceRunning&&section.dataset.motion!=='paused'))wake();}
function wake(){if(!frame&&visible&&!document.hidden)frame=requestAnimationFrame(draw)}
function resize(){const box=section.querySelector('.woven-network').getBoundingClientRect();width=box.width;height=box.height;mobile=innerWidth<=700;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);refresh()}
new ResizeObserver(resize).observe(section);new IntersectionObserver(e=>{visible=e[0].isIntersecting;if(!visible){cancelAnimationFrame(frame);frame=0;traceLast=0}else wake()},{threshold:.01}).observe(section);
new MutationObserver(wake).observe(section,{attributes:true,attributeFilter:['data-motion']});section.querySelector('img.art').addEventListener('load',resize);document.addEventListener('visibilitychange',wake);resize();
const fabricImage=section.querySelector('img.art');fabricImage.addEventListener('load',embedLights,{once:true});if(fabricImage.complete)embedLights();
})();
